// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe69wiKaopnCwaVmtbP5B6KN8V9ewDkaE',
    appId: '1:319442119788:web:e0befc23b8ae7a8dffbc49',
    messagingSenderId: '319442119788',
    projectId: 'brick-bhatta-36052',
    authDomain: 'brick-bhatta-36052.firebaseapp.com',
    storageBucket: 'brick-bhatta-36052.firebasestorage.app',
    measurementId: 'G-FYXX4R9P53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8bpoT0DNBtIC4ssu-rHt8E4T2xKkCHD4',
    appId: '1:319442119788:android:10d5ff4595fab2e2ffbc49',
    messagingSenderId: '319442119788',
    projectId: 'brick-bhatta-36052',
    storageBucket: 'brick-bhatta-36052.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMZON7FOFSyDU5miAY0QaWizakGFlupZ0',
    appId: '1:319442119788:ios:1cb8b6353e0e2f8affbc49',
    messagingSenderId: '319442119788',
    projectId: 'brick-bhatta-36052',
    storageBucket: 'brick-bhatta-36052.firebasestorage.app',
    iosBundleId: 'com.brickbhattamanagementsystem.brickBhattaManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMZON7FOFSyDU5miAY0QaWizakGFlupZ0',
    appId: '1:319442119788:ios:1cb8b6353e0e2f8affbc49',
    messagingSenderId: '319442119788',
    projectId: 'brick-bhatta-36052',
    storageBucket: 'brick-bhatta-36052.firebasestorage.app',
    iosBundleId: 'com.brickbhattamanagementsystem.brickBhattaManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe69wiKaopnCwaVmtbP5B6KN8V9ewDkaE',
    appId: '1:319442119788:web:b14004dda49a965fffbc49',
    messagingSenderId: '319442119788',
    projectId: 'brick-bhatta-36052',
    authDomain: 'brick-bhatta-36052.firebaseapp.com',
    storageBucket: 'brick-bhatta-36052.firebasestorage.app',
    measurementId: 'G-9640ZTQ7MY',
  );

}