// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUrrH8qbeNyxhQ6iTGS0ypjx5GSCrlhP8',
    appId: '1:79355426622:web:ccdd98bd5a1498afa91e6f',
    messagingSenderId: '79355426622',
    projectId: 'brick-bhatta-8915f',
    authDomain: 'brick-bhatta-8915f.firebaseapp.com',
    storageBucket: 'brick-bhatta-8915f.firebasestorage.app',
    measurementId: 'G-LZPJE8TYWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnjlciCDbe482kfwnCyW6SXzZkJTh3pDY',
    appId: '1:79355426622:android:6435c14c636f2e8ea91e6f',
    messagingSenderId: '79355426622',
    projectId: 'brick-bhatta-8915f',
    storageBucket: 'brick-bhatta-8915f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1yNK8Z9hWIObF6BUPvgPc2Ta8npHYU4k',
    appId: '1:79355426622:ios:96a313a02c74d02da91e6f',
    messagingSenderId: '79355426622',
    projectId: 'brick-bhatta-8915f',
    storageBucket: 'brick-bhatta-8915f.firebasestorage.app',
    iosBundleId: 'com.brickbhattamanagementsystem.brickBhattaManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1yNK8Z9hWIObF6BUPvgPc2Ta8npHYU4k',
    appId: '1:79355426622:ios:96a313a02c74d02da91e6f',
    messagingSenderId: '79355426622',
    projectId: 'brick-bhatta-8915f',
    storageBucket: 'brick-bhatta-8915f.firebasestorage.app',
    iosBundleId: 'com.brickbhattamanagementsystem.brickBhattaManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUrrH8qbeNyxhQ6iTGS0ypjx5GSCrlhP8',
    appId: '1:79355426622:web:4dc27140aa67e2e2a91e6f',
    messagingSenderId: '79355426622',
    projectId: 'brick-bhatta-8915f',
    authDomain: 'brick-bhatta-8915f.firebaseapp.com',
    storageBucket: 'brick-bhatta-8915f.firebasestorage.app',
    measurementId: 'G-SVFSZ8EFCC',
  );

}